package com.onesoft.jaydenim.model;


import com.onesoft.jaydenim.R;
import com.onesoft.jaydenim.domain.EaseEmojicon;
import com.onesoft.jaydenim.domain.EaseEmojicon.Type;
import com.onesoft.jaydenim.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {
    
    private static String[] emojis = new String[]{
        EaseSmileUtils.ee_0,
        EaseSmileUtils.ee_1,
        EaseSmileUtils.ee_2,
        EaseSmileUtils.ee_3,
        EaseSmileUtils.ee_4,
        EaseSmileUtils.ee_5,
        EaseSmileUtils.ee_6,
        EaseSmileUtils.ee_7,
        EaseSmileUtils.ee_8,
        EaseSmileUtils.ee_9,
        EaseSmileUtils.ee_10,
        EaseSmileUtils.ee_11,
        EaseSmileUtils.ee_12,
        EaseSmileUtils.ee_13,
        EaseSmileUtils.ee_14,
        EaseSmileUtils.ee_15,
        EaseSmileUtils.ee_16,
        EaseSmileUtils.ee_17,
        EaseSmileUtils.ee_18,
        EaseSmileUtils.ee_19,
        EaseSmileUtils.ee_20,
        EaseSmileUtils.ee_21,
        EaseSmileUtils.ee_22,
        EaseSmileUtils.ee_23,
        EaseSmileUtils.ee_24,
        EaseSmileUtils.ee_25,
        EaseSmileUtils.ee_26,
        EaseSmileUtils.ee_27,
        EaseSmileUtils.ee_28,
        EaseSmileUtils.ee_29,
        EaseSmileUtils.ee_30,
        EaseSmileUtils.ee_31,
        EaseSmileUtils.ee_32,
        EaseSmileUtils.ee_33,
        EaseSmileUtils.ee_34,
        EaseSmileUtils.ee_35,
        EaseSmileUtils.ee_36,
        EaseSmileUtils.ee_37,
        EaseSmileUtils.ee_38,
        EaseSmileUtils.ee_39,
        EaseSmileUtils.ee_40,
        EaseSmileUtils.ee_41,
        EaseSmileUtils.ee_42,
        EaseSmileUtils.ee_43,
        EaseSmileUtils.ee_44,
        EaseSmileUtils.ee_45,
        EaseSmileUtils.ee_46,
        EaseSmileUtils.ee_47,
        EaseSmileUtils.ee_48,
        EaseSmileUtils.ee_49,
        EaseSmileUtils.ee_50,
        EaseSmileUtils.ee_51,
        EaseSmileUtils.ee_52,
        EaseSmileUtils.ee_53,
        EaseSmileUtils.ee_54,
        EaseSmileUtils.ee_55,
        EaseSmileUtils.ee_56,
        EaseSmileUtils.ee_57,
        EaseSmileUtils.ee_58,
        EaseSmileUtils.ee_59,
        EaseSmileUtils.ee_60,
        EaseSmileUtils.ee_61,
        EaseSmileUtils.ee_62,
        EaseSmileUtils.ee_63,
        EaseSmileUtils.ee_64,
        EaseSmileUtils.ee_65,
        EaseSmileUtils.ee_66,
        EaseSmileUtils.ee_67,
        EaseSmileUtils.ee_68,
        EaseSmileUtils.ee_69,
        EaseSmileUtils.ee_70,
        EaseSmileUtils.ee_71,
        EaseSmileUtils.ee_72,
        EaseSmileUtils.ee_73,
        EaseSmileUtils.ee_74,
        EaseSmileUtils.ee_75,
        EaseSmileUtils.ee_76,
        EaseSmileUtils.ee_77,
        EaseSmileUtils.ee_78,
        EaseSmileUtils.ee_79,
        EaseSmileUtils.ee_80,
        EaseSmileUtils.ee_81,
        EaseSmileUtils.ee_82,
        EaseSmileUtils.ee_83,
        EaseSmileUtils.ee_84,
        EaseSmileUtils.ee_85,
        EaseSmileUtils.ee_86,
        EaseSmileUtils.ee_87,
        EaseSmileUtils.ee_88,
        EaseSmileUtils.ee_89,
        EaseSmileUtils.ee_90,
        EaseSmileUtils.ee_91,
        EaseSmileUtils.ee_92,
            EaseSmileUtils.ee_93,
            EaseSmileUtils.ee_94,
            EaseSmileUtils.ee_95,
            EaseSmileUtils.ee_96,
            EaseSmileUtils.ee_97,
            EaseSmileUtils.ee_98,
            EaseSmileUtils.ee_99,
            EaseSmileUtils.ee_100,
            EaseSmileUtils.ee_101,
            EaseSmileUtils.ee_102,
            EaseSmileUtils.ee_103,
            EaseSmileUtils.ee_104,
    };
    
    private static int[] icons = new int[]{
        R.drawable.e000,
        R.drawable.e001,
        R.drawable.e002,
        R.drawable.e003,
        R.drawable.e004,
        R.drawable.e005,
        R.drawable.e006,
        R.drawable.e007,
        R.drawable.e008,
        R.drawable.e009,
        R.drawable.e010,
        R.drawable.e011,
        R.drawable.e012,
        R.drawable.e013,
        R.drawable.e014,
        R.drawable.e015,
        R.drawable.e016,
        R.drawable.e017,
        R.drawable.e018,
        R.drawable.e019,
        R.drawable.e020,
        R.drawable.e021,
        R.drawable.e022,
        R.drawable.e023,
        R.drawable.e024,
        R.drawable.e025,
        R.drawable.e026,
        R.drawable.e027,
        R.drawable.e028,
        R.drawable.e029,
        R.drawable.e030,
        R.drawable.e031,
        R.drawable.e032,
        R.drawable.e033,
        R.drawable.e034,
        R.drawable.e035,
        R.drawable.e036,
        R.drawable.e037,
        R.drawable.e038,
        R.drawable.e039,
        R.drawable.e040,
        R.drawable.e041,
        R.drawable.e042,
        R.drawable.e043,
        R.drawable.e044,
        R.drawable.e045,
        R.drawable.e046,
        R.drawable.e047,
        R.drawable.e048,
        R.drawable.e049,
        R.drawable.e050,
        R.drawable.e051,
        R.drawable.e052,
        R.drawable.e053,
        R.drawable.e054,
        R.drawable.e055,
        R.drawable.e056,
        R.drawable.e057,
        R.drawable.e058,
        R.drawable.e059,
        R.drawable.e060,
        R.drawable.e061,
        R.drawable.e062,
        R.drawable.e063,
        R.drawable.e064,
        R.drawable.e065,
        R.drawable.e066,
        R.drawable.e067,
        R.drawable.e068,
        R.drawable.e069,
        R.drawable.e070,
        R.drawable.e071,
        R.drawable.e072,
        R.drawable.e073,
        R.drawable.e074,
        R.drawable.e075,
        R.drawable.e076,
        R.drawable.e077,
        R.drawable.e078,
        R.drawable.e079,
        R.drawable.e080,
        R.drawable.e081,
        R.drawable.e082,
        R.drawable.e083,
        R.drawable.e084,
        R.drawable.e085,
        R.drawable.e086,
        R.drawable.e087,
        R.drawable.e088,
        R.drawable.e089,
        R.drawable.e090,
        R.drawable.e091,
        R.drawable.e092,
        R.drawable.e093,
        R.drawable.e094,
        R.drawable.e095,
        R.drawable.e096,
        R.drawable.e097,
        R.drawable.e098,
        R.drawable.e099,
        R.drawable.e100,
        R.drawable.e101,
        R.drawable.e102,
        R.drawable.e103,
        R.drawable.e104,
    };
    
    
    private static final EaseEmojicon[] DATA = createData();
    
    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }
    
    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
